version: "3.9"
services:

  database:
    image: postgres
    environment:
      POSTGRES_HOST: "localhost"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345678"
      POSTGRES_DB: "postgres"
    volumes:
      - ./apps/backend/api/db/seed.sql:/docker-entrypoint-initdb.d/seed.sql

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    image: tstmaker/frontend
    ports:
      - "4200:4200"
    depends_on:
      - "database"
    volumes:
      - /app/node_modules
      - ./apps/frontend:/app

  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    image: tstmaker/backend
    environment:
      DATABASE_DB: "postgres"
      DATABASE_HOST: "database"
      DATABASE_PORT: "5432"
      DATABASE_USER: "postgres"
      DATABASE_PASSWORD: "12345678"
    ports:
      - "5000:5000"
    depends_on:
      - "database"
      - "frontend"
    volumes:
      - ./apps/backend:/app