CREATE TABLE Exercises (
  id SERIAL PRIMARY KEY NOT NULL,
  name TEXT DEFAULT '' NOT NULL,
  description TEXT DEFAULT '' NOT NULL,
  code TEXT DEFAULT '' NOT NULL,
  last_modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
