[tool.autopep8]
max-line-length = 200
indent-size = 2
exclude = "Definiciones.py"
in-place = true
recursive = true
aggressive = 3

[tool.flake8]
max-line-length = 200
indent-size = 2
exclude = "Definiciones.py"

[tool.pytest.ini_options]
addopts = "-ra -q"
testpaths = ["**/__tests__/test_*.py"]
